"""
Django settings for innes_cuarto_pruebas project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fllqbh**1&g_0ne=l)&)t@au@#=5k!yc20q-tn1ywaz_d%6m+_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# --- BACnet (PR_0003) ---
# Defaults de configuración BACnet (single-row en la UI Admin)
# Nota: estos valores son defaults. La UI debe permitir editarlos y persistirlos.
def _env_int(name: str, default: int) -> int:
    v = os.getenv(name)
    return default if v in (None, "") else int(v)

def _env_str(name: str, default: str) -> str:
    v = os.getenv(name)
    return default if v in (None, "") else v

BACNET_DEFAULTS = {
    "bind_ip": _env_str("BACNET_BIND_IP", "127.0.0.1"),
    "mask": _env_str("BACNET_MASK", "24"),
    "local_port": _env_int("BACNET_LOCAL_PORT", 47808),
    "broadcast": _env_str("BACNET_BROADCAST", "*:*"),
    "timeout_seconds": _env_int("BACNET_TIMEOUT_SECONDS", 3),
    "retries": _env_int("BACNET_RETRIES", 2),
    "discovery_interval_sec": _env_int("BACNET_DISCOVERY_INTERVAL_SEC", 30),
    "offline_threshold_broadcast_cycles": _env_int("BACNET_OFFLINE_THRESHOLD_BROADCAST_CYCLES", 2),
    "write_priority_default": _env_int("BACNET_WRITE_PRIORITY_DEFAULT", 8),
    "bbmd_enabled": os.getenv("BACNET_BBMD_ENABLED", "0") == "1",
    "bbmd_address": os.getenv("BACNET_BBMD_ADDRESS") or None,
    "foreign_device_enabled": os.getenv("BACNET_FOREIGN_DEVICE_ENABLED", "0") == "1",
    "foreign_device_bbmd_address": os.getenv("BACNET_FOREIGN_DEVICE_BBMD_ADDRESS") or None,
    "foreign_device_ttl_seconds": _env_int("BACNET_FOREIGN_DEVICE_TTL_SECONDS", 600),
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home.apps.HomeConfig',
    'bacnet.apps.BacnetConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'innes_cuarto_pruebas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'innes_cuarto_pruebas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Directorio(s) adicionales donde Django buscará estáticos
STATICFILES_DIRS = [
	BASE_DIR / "statics",
]