# Generated by Django 6.0.3 on 2026-04-14 08:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacnetDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_instance', models.PositiveIntegerField(unique=True)),
                ('ip', models.CharField(max_length=64)),
                ('vendor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=128, null=True)),
                ('model_name', models.CharField(blank=True, max_length=128, null=True)),
                ('firmware', models.CharField(blank=True, max_length=128, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['device_instance'],
            },
        ),
        migrations.CreateModel(
            name='BacnetSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bind_ip', models.CharField(max_length=64)),
                ('mask', models.CharField(default='24', max_length=8)),
                ('local_port', models.PositiveIntegerField(default=47808, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('broadcast', models.CharField(default='*:*', max_length=64)),
                ('timeout_seconds', models.FloatField(default=3)),
                ('retries', models.PositiveIntegerField(default=2)),
                ('discovery_interval_sec', models.PositiveIntegerField(default=30)),
                ('offline_threshold_broadcast_cycles', models.PositiveIntegerField(default=2)),
                ('write_priority_default', models.PositiveIntegerField(default=8, help_text='Regla: 1..8 (no usar prioridad 9).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('bbmd_enabled', models.BooleanField(default=False)),
                ('bbmd_address', models.CharField(blank=True, max_length=64, null=True)),
                ('foreign_device_enabled', models.BooleanField(default=False)),
                ('foreign_device_bbmd_address', models.CharField(blank=True, max_length=64, null=True)),
                ('foreign_device_ttl_seconds', models.PositiveIntegerField(default=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BacnetAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('SCAN', 'SCAN'), ('READ_PV', 'READ_PV'), ('WRITE_PV', 'WRITE_PV'), ('RELEASE', 'RELEASE'), ('RELEASE_ALL', 'RELEASE_ALL')], max_length=32)),
                ('reason', models.TextField(blank=True, null=True)),
                ('device_instance', models.PositiveIntegerField()),
                ('object_id_str', models.CharField(max_length=64)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('result', models.CharField(default='OK', max_length=16)),
                ('technical_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BacnetObjectPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=64)),
                ('object_instance', models.PositiveIntegerField()),
                ('object_id_str', models.CharField(max_length=64)),
                ('object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=64, null=True)),
                ('historical_enabled', models.BooleanField(default=False)),
                ('historical_interval_sec', models.PositiveIntegerField(default=5)),
                ('historical_sample_interval_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='bacnet.bacnetdevice')),
            ],
            options={
                'ordering': ['device', 'object_type', 'object_instance'],
            },
        ),
        migrations.CreateModel(
            name='BacnetPointSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('quality', models.CharField(default='OK', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='bacnet.bacnetobjectpoint')),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.AddConstraint(
            model_name='bacnetobjectpoint',
            constraint=models.UniqueConstraint(fields=('device', 'object_id_str'), name='uniq_point_per_device'),
        ),
        migrations.AddIndex(
            model_name='bacnetpointsample',
            index=models.Index(fields=['point', 'ts'], name='bacnet_bacn_point_i_a87927_idx'),
        ),
    ]
